# Generated by Django 3.0.6 on 2020-07-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher'), ('HTE', 'Headteacher')], default='ST', max_length=3),
        ),
    ]
