# Generated by Django 3.0.6 on 2020-07-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_state',
            new_name='user_status',
        ),
    ]
