# Generated by Django 3.0.6 on 2020-07-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200708_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('headteacher', 'Headteacher')], max_length=11, verbose_name='user_status'),
        ),
    ]
