# Generated by Django 3.0.6 on 2020-07-07 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subject', models.CharField(choices=[('MA', 'Math'), ('ENG', 'English'), ('BIO', 'Biology')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[("('1', (('1A', '1A'), ('1B', '1B')))", 'First'), ("('2', (('2A', '2A'), ('2B', '2B')))", 'Second')], max_length=100, unique=True)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_system.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_system.Teacher')),
            ],
        ),
    ]
