# Generated by Django 3.0.6 on 2020-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0003_auto_20200709_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(choices=[('A', 'One A'), ('1B', 'One B'), ('1C', 'One C'), ('2A', 'Two A'), ('2B', 'Two B'), ('2C', 'Two C')], default='XXXXXX', max_length=100, unique=True),
        ),
    ]
